version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`. (You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.)
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    open-pull-requests-limit: 20
    groups:
      ci-dependencies:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    open-pull-requests-limit: 20
    groups:
      code-dependencies:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"

  # Maintain dependencies for Docker images
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    open-pull-requests-limit: 20
    groups:
      docker-dependencies:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
